#!/usr/bin/awk -f
#
# This script is written to total marks based on a csv file from the Blackboard
# Learn software suite. Its use is LIMITED TO assessments where all the
# multiple choice questions were put in a seperate BB test.  Additionally, it
# requires that output from ClickUP be in the SHORT format, i.e. grouping by
# students	only


BEGIN {

	# set configuration variables that might break if BB ever changes their
	# export format but it's simple enough reconfigure.
	initial = 8
	distance = 6
	FS = ","

}

# define function that totals student marks
function grade(sum) {
	columns = split($0, entry, ",")	# create an array from the records of the csv file
	questions =  ( columns - 3 ) / distance
	for ( i = 0; i < questions; i++ ) {
		if (entry[initial+i*distance] == "\"1\") sum += 1
	}
	return sum
}

FNR == 1	{
			print $1 "," $2 "," $3 "," "\"Grade[" questions "]\""
		}

FNR > 1	{
			prefix = $1 "," $2 "," $3 ","
			print prefix grade(0)
		}
